<?php

namespace UrlShortenerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShortLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortLinkRepository extends EntityRepository
{
}
